travis:
  secure:
    BINSTAR_TOKEN: H4jliCFTIrhZV9g9p4SED2pJOYMRqSk4vJbbDxF+JLzo0tx9FTicLMG1PiP3Es9mJ0g/KFdl+Ars7ZM4bBHy9Bj/5kjj8gHJDGgop2Mx3ib8v3ammpZSoHbhVdYvcsNviVaRTm/eZ1oJoM3+Cd7Gfs2fgOxf1d1UvtAq2jgeA7zKLFXFXrDoCWktbnkl2QRWvj7N4bbFSGcpvAEdCaOQk1I6ogl4B7R4fG58trWnpUnX5N+PW6X09vbNXukcTLrpyUkJOOk1BbBg7qTdL0GVx5sBUIZgV8NeY2VCSiBDt8amD4ysE+FVEyedxpErOg1IKt4483ami8scwy2++w9U4I0kT0VgBRhXj07iJHym0342uO4QOPoghsvlLjwJfGLJZ/ELfTmSNERYw+qvHkPznJoIkLeyjH6QGVMjd1AgwVYidsrmYzzw96tzfPWgY3UzKE0hCaH5OLdd65znMwNNzfSUMOpTmsUvF+WJVLwKc38IFBRKYGtFIJhVtXh2+iDTLg23mqd1Bm2qAJ0PPcXtK525P0Lj1WqoHxHzDdFmrVvClLT+Sg+nTS3f5d5mV2x05VSF6qRxeQvBZpPrZ3G3mXlQvDXgmttdD4zVsAz9Z3rmENginp0ObF0cdvNIVFphsGcGLhefs7isduow1J79ysUqXTr8jREDkifK7aOnC8M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
